### ISSUE TITLE
Add autocomplete to tags input with tags currently being used

### ISSUE THREAD

**Issue by CodyGramlich** [yeg-relief/youcanbenefit#101]
When you add tags to a program, you often want the tags to be the same as the tags of other programs. I think it would be useful to have autocomplete with the tags input with a list of tags that are currently being used. When you click on the input, then a list of all the tags would show up giving you the option to either select a tag that's already in use or create a new tag.

**Comment by j-rewerts** [comment]
Closed with #102 .
