### ISSUE TITLE
Give keys description

### ISSUE THREAD

**Issue by j-rewerts** [yeg-relief/youcanbenefit#12]
Currently, it's difficult to tell what keys where created for. If we could add a description, that would make things easier to understand.

**Comment by kylecjo** [comment]
working on this

**Comment by kylecjo** [comment]
Currently all the key information is stored as a mapping in elasticsearch, which works for the current use which only needs a key name and key type. But I think if we want to store description as well, the keys would have to be stored as documents, and that might take some work.

**Comment by kylecjo** [comment]
I think I found a solution, elasticsearch allows a  _meta mapping type that is used to store application-specific metadata. A key value pair of name: description can be kept in the _meta field and and retrieved when needed.

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping-meta-field.html

**Comment by j-rewerts** [comment]
Closing in lieu of #41 .
