### ISSUE TITLE
Pass environment variables to frontend app

### ISSUE THREAD

**Issue by j-rewerts** [yeg-relief/youcanbenefit#15]
It's easy to pass configuration to the backend through Docker. This makes configuring and creating new containers easy. It's a bit trickier in frontend apps. See [here](https://stackoverflow.com/questions/48595829/how-to-pass-environment-variables-to-a-frontend-web-application) for some discussion on how to do it.

**Comment by slmyers** [comment]
I typically pass `env` variables at buildtime using `webpack#definePlugin`. Angular CLI abstracts the webpack configuration file, so to do the same thing with angular you would do something like [this](https://blog.usejournal.com/system-environment-variables-in-angular-1f4a922c7b4c).

**Comment by j-rewerts** [comment]
Closing for now. Will reopen and use @slmyers suggestion if needed.
