### ISSUE TITLE
Range conditions

### ISSUE THREAD

**Issue by farhadmak** [yeg-relief/youcanbenefit#16]
**use case:**

> Is there a way to input an income query result as a range? I am working with the new Leisure Access Program and for people over the base amount but under another amount they will be eligible the Leisure Access Pass Lite. I would like to set it up so that for people eligible for the regular LAP they won’t see the Lite version (less confusing that way) but can’t seem to figure out how to set a minimum AND maximum income amount.

**requires:**

1. Making a new condition type in Query object.
2. Building UI to support constructing such a condition.
3. testing the feature.

**Comment by kylecjo** [comment]
Isn't it possible to add one multiple conditions multiple times when creating a query? So you can add a condition "gross income >=" and another condition "gross income <=" to get a range. 

![screen shot 2018-11-16 at 12 29 11 pm](https://user-images.githubusercontent.com/19258796/48642948-8d9ed700-e99b-11e8-8239-485622a109f2.png)

**Comment by farhadmak** [comment]
Oh thats true.. I definitely thought about this earlier. This was one of the issues I transferred over from the old repo. It should work.. but can we test to confirm before we close the issue? @kylecjo

**Comment by farhadmak** [comment]
#11 would come handy here

**Comment by kylecjo** [comment]
I set two conditions "grossincome <= 1 000 003" and "grossincome >= 1000 001". When filling out the questions I qualify if I enter my gross income as 1000002 but don't if I enter 1000000. I'm not sure if we want to test it more extensively than that.

**Comment by farhadmak** [comment]
Cool, closing this issue then
