### ISSUE TITLE
Ability to edit/delete keys

### ISSUE THREAD

**Issue by farhadmak** [yeg-relief/youcanbenefit#21]
Once a key is made, there is no way to delete it.

Could be an intentional design decision. Look into Elasticsearch.

**Comment by kylecjo** [comment]
Is there a 1-1 mapping between questions and keys?

**Comment by farhadmak** [comment]
Yes, once a key has been assigned to a question, it will no longer show up as a possible key to other questions

**Comment by kylecjo** [comment]
Jared suggested that we investigate being able to add/edit keys directly on the questions tab and maybe get rid of the keys one

**Comment by farhadmak** [comment]
Oh yeah, thats a pretty good idea

**Comment by slmyers** [comment]
iirc one of the issues is that you'll need to rebuild the index. 

https://stackoverflow.com/a/28871808/764384

**Comment by farhadmak** [comment]
Working on this with @kylecjo

**Comment by j-rewerts** [comment]
Fixed by @CodyGramlich with #87 .
