### ISSUE TITLE
Remove keys

### ISSUE THREAD

**Issue by j-rewerts** [yeg-relief/youcanbenefit#41]
- [ ] Use question label instead of key in program queries
- [ ] Remove Keys section
- [ ] Replace input type "type" with Number Input or something similar
- [ ] Infer key type from question input type
- [ ] Add input type to nested multiselect questions

This issue will break the City of Edmonton's current YCB schema. We will need to write a script to transform it to the new keyless schema.

**Comment by j-rewerts** [comment]
@slmyers With this issue, we're trying to completely get rid of keys. Is there any reason you think this couldn't be done?

**Comment by slmyers** [comment]
The keys are index mappings. So, I guess if you infer keys from input types and then use that to map the index, it should be good. 

index mappings ~~ db schema

https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html

**Comment by j-rewerts** [comment]
Fixed by @CodyGramlich with #87.
