### ISSUE TITLE
Fix event-stream vulnerability

### ISSUE THREAD

**Issue by j-rewerts** [yeg-relief/youcanbenefit#42]
There is a critical issue in event-stream. See [here](https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident).

**Comment by slmyers** [comment]
Windows defender will alert when you `npm install`

![image](https://user-images.githubusercontent.com/6344732/50368303-79269f00-0544-11e9-98b8-c464d0a29743.png)

**Comment by slmyers** [comment]
will be fixed with (#32)

**Comment by j-rewerts** [comment]
Fixed with #47 .
