### ISSUE TITLE
Add rich text editing to program info

### ISSUE THREAD

**Issue by j-rewerts** [yeg-relief/youcanbenefit#43]
Requested by Katie Walker.

**Comment by j-rewerts** [comment]
I'll be working with @TheBroMoe on this one.

**Comment by CodyGramlich** [comment]
@j-rewerts 
This is what I'm trying out. Seems pretty good so far.
https://quilljs.com/
https://github.com/KillerCodeMonkey/ngx-quill

**Comment by j-rewerts** [comment]
Awesome! Let me know if you need any help. Also feel free to ask @TheBroMoe for help with the backend if needed.
