### ISSUE TITLE
Add a favicon

### ISSUE THREAD

**Issue by j-rewerts** [yeg-relief/youcanbenefit#49]

**Comment by CodyGramlich** [comment]
Unable to post .ico files here.

**Comment by j-rewerts** [comment]
I'd like the ico to have a few features:

- [ ] Slight margin around the outside
- [ ] Transparent background
- [ ] The letters YCB

**Comment by CodyGramlich** [comment]
I made the magnifying glass one have a transparent background and made one with the letters YCB which look like

![favicon_magnify_ss](https://user-images.githubusercontent.com/32050152/51578233-10e81780-1e7a-11e9-8cd0-74663833e249.PNG)

and

![favicon_ycb_ss](https://user-images.githubusercontent.com/32050152/51578252-1e050680-1e7a-11e9-800e-2f59f334010e.PNG)

I'm not sure what you mean by slight margin. Let me know what you think of these and if I should make some changes to the one with the YCB letters.

**Comment by j-rewerts** [comment]
Submit a PR when you get a chance!

**Comment by CodyGramlich** [comment]
Closed with [#56](https://github.com/yeg-relief/youcanbenefit/pull/56)
