### ISSUE TITLE
Change default search for program to "search title"

### ISSUE THREAD

**Issue by CodyGramlich** [yeg-relief/youcanbenefit#52]
Currently the search option is set to "search disabled" by default. Also, when the "search title" option is selected, no programs are listed initially. We would want it to list all the programs by default and then the user can enter in text as a filter.

**Comment by slmyers** [comment]
Is this in the `admin/program` section? The issue is that a search on a page where all the content is displayed (we show all programs) is not much use, because of `ctrl+f`. I would low priority this.

**Comment by CodyGramlich** [comment]
Yes, in the `admin/program` section. I have often been using `ctrl+f` to find programs here, but it was mentioned by one of the social workers who are using it. I said that we could probably change it.
